### ISSUE TITLE
Not same resultat

### ISSUE THREAD

**Issue by hugoclo** [miroslavvidovic/tmdb-bash#3]
Hello
When I type this command: ./tmdb.sh -y 2017 "The Mummy"
I have this resutat : 
```
"page": 1,
  "total_results": 7, 
  "total_pages": 1,
  "results": [
```
I don't have only one result
Thx

**Comment by mskian** [comment]
check From my side got the correct result

**Comment by miroslavvidovic** [comment]
Hi @hugoclo . Can you run the command with debug mode enabled 
`bash -x tmdb.sh -y 2017 "The Mummmy"`
and paste the result here so we can try to reproduce the issue you are having?

**Comment by hugoclo** [comment]
Hello,
It's me who was wrong. Thank you.
